# Generated by Django 2.2.1 on 2019-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=100)),
                ('corporate_code', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_no', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=100)),
                ('has_auth_level', models.BooleanField()),
                ('has_assessment_codes', models.BooleanField()),
                ('is_radio', models.BooleanField()),
                ('is_local', models.BooleanField()),
                ('is_outstation', models.BooleanField()),
                ('is_bus', models.BooleanField()),
                ('is_train', models.BooleanField()),
                ('is_hotel', models.BooleanField()),
                ('is_meal', models.BooleanField()),
                ('is_flight', models.BooleanField()),
                ('is_water_bottles', models.BooleanField()),
                ('is_reverse_logistics', models.BooleanField()),
            ],
            options={
                'db_table': 'corporates',
            },
        ),
        migrations.CreateModel(
            name='Corporate_Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'corporate_agents',
            },
        ),
        migrations.CreateModel(
            name='Corporate_Approves_1_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('corporate_id', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'corporate_subgroup_authenticater',
            },
        ),
        migrations.CreateModel(
            name='Corporate_Approves_2_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('corporate_id', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'corporate_group_authenticator',
            },
        ),
        migrations.CreateModel(
            name='Corporate_Spoc_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('corporate_id', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'corporate_spocs',
            },
        ),
        migrations.AddField(
            model_name='corporate_login',
            name='contact_no',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='corporate_login',
            name='corporate_id',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='corporate_login',
            name='last_login',
            field=models.DateTimeField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='corporate_login',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='corporate_login',
            name='email',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
